apiVersion: v2
name: nagvis2
description: NagVis 2 – Network Monitoring Visualization
type: application
version: 0.1.0
appVersion: "2.0-beta"
keywords:
  - nagvis
  - monitoring
  - visualization
  - nagios
  - checkmk
home: https://github.com/bh2005/nagvis-kurz-vor-2
maintainers:
  - name: NagVis 2 Contributors
